const HTTP_STATUS_CODES = {
  HTTP_STATUS_OK: 200,
  HTTP_STATUS_CREATED: 201,
  HTTP_STATUS_NO_CONTENT: 204,
  HTTP_STATUS_BAD_REQUEST: 400,
  HTTP_STATUS_UNAUTHORIZED: 401,
  HTTP_STATUS_NOT_FOUND: 404,
  HTTP_STATUS_INVALID_ARGUMENT: 422,
  HTTP_STATUS_INTERNAL_SERVER: 500,
};

module.exports = HTTP_STATUS_CODES;